import { StyleSheet } from 'react-native';

export const HeaderComponentStyles = StyleSheet.create({
  header: {
    backgroundColor: '#2f9b2e',
    paddingHorizontal: 20,
    paddingTop: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 4,
    height: 72,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginTop: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    color: '#fff',
    maxWidth: '90%',
    flexShrink: 1,
    textAlign: 'center',
    lineHeight: 26,
  },
  menuButton: {
    marginTop: 5,
  },
  menuIcon: {
    fontSize: 28,
    color: '#fff',
    fontWeight: 'bold',
  },
  drawerOverlay: {
    position: 'absolute',
    top: 72,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 999,
  },
  drawer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 280,
    backgroundColor: '#fff',
    zIndex: 1000,
    elevation: 16,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  drawerHeader: {
    backgroundColor: '#3fbb34',
    padding: 20,
    paddingTop: 50,
  },
  drawerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  menuItem: {
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  menuItemText: {
    fontSize: 16,
    color: '#333',
  },
  themeToggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#f8f8f8',
  },
  closeButton: {
    backgroundColor: '#007bff',
    borderRadius: 8,
    marginTop: 20,
    borderBottomWidth: 0,
  },
  closeButtonText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  gestureArea: {
    position: 'absolute',
    left: 0,
    top: 72,
    bottom: 0,
    width: 20,
    zIndex: 100,
  },
});
