import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../../context/ThemeContext';

const { width } = Dimensions.get('window');

export const createAudioVideoStyles = (colors: Colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
    padding: 15,
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  cardHeader: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  carouselContainer: {
    alignItems: 'center',
    marginVertical: 20,
    backgroundColor: colors.cardBackground,
    borderRadius: 12,
    padding: 15,
  },
  carouselImage: {
    width: width - 90,
    height: 280,
    borderRadius: 10,
  },
  descripcionContainer: {
    marginBottom: 20,
  },
  descripcionTextContainer: {
    backgroundColor: colors.cardBackground,
    padding: 15,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 12,
  },
  descripcionText: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
    textAlign: 'justify',
  },
  especificacionesContainer: {
    marginBottom: 20,
    padding: 0,
  },
  listaContainer: {
    gap: 12,
  },
  listaItem: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  counterContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.cardBackground,
    padding: 15,
    borderRadius: 10,
    marginBottom: 25,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  counterText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  submitButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.overlay,
  },
  modalContent: {
    backgroundColor: colors.modalBackground,
    borderRadius: 20,
    padding: 28,
    width: width - 120,
    maxWidth: width,
    minHeight: 800,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: colors.textPrimary,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 7,
    marginBottom: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    width: '100%',
    minWidth: '100%',
    fontSize: 14,
    backgroundColor: colors.inputBackground,
    color: colors.textPrimary,
  },
  modalText: {
    fontSize: 14,
    marginBottom: 8,
    alignSelf: 'flex-start',
    color: colors.textPrimary,
  },
  pickerInput: {
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 7,
    marginBottom: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
    width: '100%',
    minWidth: '100%',
    backgroundColor: colors.inputBackground,
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: 'bold',
  },
});
